<?php

if (!defined('ABSPATH')) {
    exit();
}

global $forms_bridge_dolibarr_countries;
$forms_bridge_dolibarr_countries = [
    ['value' => '30', 'label' => __('Afghanistan', 'forms-bridge')],
    ['value' => '31', 'label' => __('Åland Islands', 'forms-bridge')],
    ['value' => '32', 'label' => __('Albania', 'forms-bridge')],
    ['value' => '13', 'label' => __('Algeria', 'forms-bridge')],
    ['value' => '33', 'label' => __('American Samoa', 'forms-bridge')],
    ['value' => '34', 'label' => __('Andorra', 'forms-bridge')],
    ['value' => '35', 'label' => __('Angola', 'forms-bridge')],
    ['value' => '36', 'label' => __('Anguilla', 'forms-bridge')],
    ['value' => '37', 'label' => __('Antarctica', 'forms-bridge')],
    ['value' => '38', 'label' => __('Antigua and Barbuda', 'forms-bridge')],
    ['value' => '23', 'label' => __('Argentina', 'forms-bridge')],
    ['value' => '39', 'label' => __('Armenia', 'forms-bridge')],
    ['value' => '40', 'label' => __('Aruba', 'forms-bridge')],
    ['value' => '28', 'label' => __('Australia', 'forms-bridge')],
    ['value' => '41', 'label' => __('Austria', 'forms-bridge')],
    ['value' => '42', 'label' => __('Azerbaijan', 'forms-bridge')],
    ['value' => '43', 'label' => __('Bahamas', 'forms-bridge')],
    ['value' => '44', 'label' => __('Bahrain', 'forms-bridge')],
    ['value' => '45', 'label' => __('Bangladesh', 'forms-bridge')],
    ['value' => '46', 'label' => __('Barbados', 'forms-bridge')],
    ['value' => '47', 'label' => __('Belarus', 'forms-bridge')],
    ['value' => '2', 'label' => __('Belgium', 'forms-bridge')],
    ['value' => '48', 'label' => __('Belize', 'forms-bridge')],
    ['value' => '49', 'label' => __('Benin', 'forms-bridge')],
    ['value' => '50', 'label' => __('Bermuda', 'forms-bridge')],
    ['value' => '51', 'label' => __('Bhutan', 'forms-bridge')],
    ['value' => '52', 'label' => __('Bolivia', 'forms-bridge')],
    ['value' => '53', 'label' => __('Bosnia and Herzegovina', 'forms-bridge')],
    ['value' => '54', 'label' => __('Botswana', 'forms-bridge')],
    ['value' => '56', 'label' => __('Brazil', 'forms-bridge')],
    [
        'value' => '57',
        'label' => __('British Indian Ocean Territory', 'forms-bridge'),
    ],
    ['value' => '58', 'label' => __('Brunei Darussalam', 'forms-bridge')],
    ['value' => '59', 'label' => __('Bulgaria', 'forms-bridge')],
    ['value' => '60', 'label' => __('Burkina Faso', 'forms-bridge')],
    ['value' => '61', 'label' => __('Burundi', 'forms-bridge')],
    ['value' => '62', 'label' => __('Cambodia', 'forms-bridge')],
    ['value' => '24', 'label' => __('Cameroon', 'forms-bridge')],
    ['value' => '14', 'label' => __('Canada', 'forms-bridge')],
    ['value' => '63', 'label' => __('Cape Verde', 'forms-bridge')],
    ['value' => '64', 'label' => __('Cayman Islands', 'forms-bridge')],
    [
        'value' => '65',
        'label' => __('Central African Republic', 'forms-bridge'),
    ],
    ['value' => '66', 'label' => __('Chad', 'forms-bridge')],
    ['value' => '67', 'label' => __('Chile', 'forms-bridge')],
    ['value' => '9', 'label' => __('China', 'forms-bridge')],
    ['value' => '68', 'label' => __('Christmas Island', 'forms-bridge')],
    ['value' => '69', 'label' => __('Cocosling) Islands', 'forms-bridge')],
    ['value' => '70', 'label' => __('Colombia', 'forms-bridge')],
    ['value' => '71', 'label' => __('Comoros', 'forms-bridge')],
    ['value' => '72', 'label' => __('Congo', 'forms-bridge')],
    [
        'value' => '73',
        'label' => __('Congo, The Democratic Republic of the', 'forms-bridge'),
    ],
    ['value' => '74', 'label' => __('Cook Islands', 'forms-bridge')],
    ['value' => '75', 'label' => __('Costa Rica', 'forms-bridge')],
    ['value' => '76', 'label' => __('Croatia', 'forms-bridge')],
    ['value' => '77', 'label' => __('Cuba', 'forms-bridge')],
    ['value' => '300', 'label' => __('Curaçao', 'forms-bridge')],
    ['value' => '78', 'label' => __('Cyprus', 'forms-bridge')],
    ['value' => '79', 'label' => __('Czech Republic', 'forms-bridge')],
    ['value' => '80', 'label' => __('Denmark', 'forms-bridge')],
    ['value' => '81', 'label' => __('Djibouti', 'forms-bridge')],
    ['value' => '82', 'label' => __('Dominica', 'forms-bridge')],
    ['value' => '83', 'label' => __('Dominican Republic', 'forms-bridge')],
    ['value' => '84', 'label' => __('Ecuador', 'forms-bridge')],
    ['value' => '85', 'label' => __('Egypt', 'forms-bridge')],
    ['value' => '86', 'label' => __('El Salvador', 'forms-bridge')],
    ['value' => '87', 'label' => __('Equatorial Guinea', 'forms-bridge')],
    ['value' => '88', 'label' => __('Eritrea', 'forms-bridge')],
    ['value' => '89', 'label' => __('Estonia', 'forms-bridge')],
    ['value' => '90', 'label' => __('Ethiopia', 'forms-bridge')],
    ['value' => '91', 'label' => __('Falkland Islands', 'forms-bridge')],
    ['value' => '92', 'label' => __('Faroe Islands', 'forms-bridge')],
    ['value' => '93', 'label' => __('Fiji Islands', 'forms-bridge')],
    ['value' => '94', 'label' => __('Finland', 'forms-bridge')],
    ['value' => '1', 'label' => __('France', 'forms-bridge')],
    ['value' => '95', 'label' => __('French Guiana', 'forms-bridge')],
    ['value' => '96', 'label' => __('French Polynesia', 'forms-bridge')],
    [
        'value' => '97',
        'label' => __('French Southern Territories', 'forms-bridge'),
    ],
    ['value' => '16', 'label' => __('Gabon', 'forms-bridge')],
    ['value' => '98', 'label' => __('Gambia', 'forms-bridge')],
    ['value' => '99', 'label' => __('Georgia', 'forms-bridge')],
    ['value' => '5', 'label' => __('Germany', 'forms-bridge')],
    ['value' => '100', 'label' => __('Ghana', 'forms-bridge')],
    ['value' => '101', 'label' => __('Gibraltar', 'forms-bridge')],
    ['value' => '102', 'label' => __('Greece', 'forms-bridge')],
    ['value' => '103', 'label' => __('Greenland', 'forms-bridge')],
    ['value' => '104', 'label' => __('Grenada', 'forms-bridge')],
    ['value' => '106', 'label' => __('Guam', 'forms-bridge')],
    ['value' => '107', 'label' => __('Guatemala', 'forms-bridge')],
    ['value' => '241', 'label' => __('Guernsey', 'forms-bridge')],
    ['value' => '108', 'label' => __('Guinea', 'forms-bridge')],
    ['value' => '109', 'label' => __('Guinea-Bissau', 'forms-bridge')],
    ['value' => '111', 'label' => __('Haïti', 'forms-bridge')],
    [
        'value' => '112',
        'label' => __('Heard Island and McDonald', 'forms-bridge'),
    ],
    [
        'value' => '113',
        'label' => __('Holy Seeican City State)', 'forms-bridge'),
    ],
    ['value' => '114', 'label' => __('Honduras', 'forms-bridge')],
    ['value' => '115', 'label' => __('Hong Kong', 'forms-bridge')],
    ['value' => '18', 'label' => __('Hungary', 'forms-bridge')],
    ['value' => '116', 'label' => __('Iceland', 'forms-bridge')],
    ['value' => '117', 'label' => __('India', 'forms-bridge')],
    ['value' => '118', 'label' => __('Indonesia', 'forms-bridge')],
    ['value' => '119', 'label' => __('Iran', 'forms-bridge')],
    ['value' => '120', 'label' => __('Iraq', 'forms-bridge')],
    ['value' => '8', 'label' => __('Ireland', 'forms-bridge')],
    ['value' => '242', 'label' => __('Isle of Man', 'forms-bridge')],
    ['value' => '121', 'label' => __('Israel', 'forms-bridge')],
    ['value' => '3', 'label' => __('Italy', 'forms-bridge')],
    ['value' => '21', 'label' => __('Ivory Coast', 'forms-bridge')],
    ['value' => '122', 'label' => __('Jamaica', 'forms-bridge')],
    ['value' => '123', 'label' => __('Japan', 'forms-bridge')],
    ['value' => '243', 'label' => __('Jersey', 'forms-bridge')],
    ['value' => '124', 'label' => __('Jordan', 'forms-bridge')],
    ['value' => '125', 'label' => __('Kazakhstan', 'forms-bridge')],
    ['value' => '126', 'label' => __('Kenya', 'forms-bridge')],
    ['value' => '127', 'label' => __('Kiribati', 'forms-bridge')],
    ['value' => '247', 'label' => __('Kosovo', 'forms-bridge')],
    ['value' => '130', 'label' => __('Kuwait', 'forms-bridge')],
    ['value' => '131', 'label' => __('Kyrgyzstan', 'forms-bridge')],
    ['value' => '132', 'label' => __('Lao', 'forms-bridge')],
    ['value' => '133', 'label' => __('Latvia', 'forms-bridge')],
    ['value' => '134', 'label' => __('Lebanon', 'forms-bridge')],
    ['value' => '135', 'label' => __('Lesotho', 'forms-bridge')],
    ['value' => '136', 'label' => __('Liberia', 'forms-bridge')],
    ['value' => '137', 'label' => __('Libya', 'forms-bridge')],
    ['value' => '138', 'label' => __('Liechtenstein', 'forms-bridge')],
    ['value' => '139', 'label' => __('Lithuania', 'forms-bridge')],
    ['value' => '140', 'label' => __('Luxembourg', 'forms-bridge')],
    ['value' => '141', 'label' => __('Macao', 'forms-bridge')],
    [
        'value' => '142',
        'label' => __('Macedonia, the former Yugoslav of', 'forms-bridge'),
    ],
    ['value' => '143', 'label' => __('Madagascar', 'forms-bridge')],
    ['value' => '144', 'label' => __('Malawi', 'forms-bridge')],
    ['value' => '145', 'label' => __('Malaysia', 'forms-bridge')],
    ['value' => '146', 'label' => __('Maldives', 'forms-bridge')],
    ['value' => '147', 'label' => __('Mali', 'forms-bridge')],
    ['value' => '148', 'label' => __('Malta', 'forms-bridge')],
    ['value' => '149', 'label' => __('Marshall Islands', 'forms-bridge')],
    ['value' => '151', 'label' => __('Mauritania', 'forms-bridge')],
    ['value' => '152', 'label' => __('Mauritius', 'forms-bridge')],
    ['value' => '153', 'label' => __('Mayotte', 'forms-bridge')],
    ['value' => '154', 'label' => __('Mexico', 'forms-bridge')],
    ['value' => '155', 'label' => __('Micronesia', 'forms-bridge')],
    ['value' => '156', 'label' => __('Moldova', 'forms-bridge')],
    ['value' => '27', 'label' => __('Monaco', 'forms-bridge')],
    ['value' => '157', 'label' => __('Mongolia', 'forms-bridge')],
    ['value' => '158', 'label' => __('Monserrat', 'forms-bridge')],
    ['value' => '244', 'label' => __('Montenegro', 'forms-bridge')],
    ['value' => '12', 'label' => __('Morocco', 'forms-bridge')],
    ['value' => '159', 'label' => __('Mozambique', 'forms-bridge')],
    ['value' => '160', 'label' => __('Myanmarma', 'forms-bridge')],
    ['value' => '161', 'label' => __('Namibia', 'forms-bridge')],
    ['value' => '162', 'label' => __('Nauru', 'forms-bridge')],
    ['value' => '163', 'label' => __('Nepal', 'forms-bridge')],
    ['value' => '17', 'label' => __('Netherlands', 'forms-bridge')],
    ['value' => '165', 'label' => __('New Caledonia', 'forms-bridge')],
    ['value' => '166', 'label' => __('New Zealand', 'forms-bridge')],
    ['value' => '167', 'label' => __('Nicaragua', 'forms-bridge')],
    ['value' => '168', 'label' => __('Niger', 'forms-bridge')],
    ['value' => '169', 'label' => __('Nigeria', 'forms-bridge')],
    ['value' => '170', 'label' => __('Niue', 'forms-bridge')],
    ['value' => '171', 'label' => __('Norfolk Island', 'forms-bridge')],
    ['value' => '128', 'label' => __('North Korea', 'forms-bridge')],
    [
        'value' => '172',
        'label' => __('Northern Mariana Islands', 'forms-bridge'),
    ],
    ['value' => '173', 'label' => __('Norway', 'forms-bridge')],
    ['value' => '174', 'label' => __('Oman', 'forms-bridge')],
    ['value' => '175', 'label' => __('Pakistan', 'forms-bridge')],
    ['value' => '176', 'label' => __('Palau', 'forms-bridge')],
    [
        'value' => '177',
        'label' => __('Palestinian Territory, Occupied', 'forms-bridge'),
    ],
    ['value' => '178', 'label' => __('Panama', 'forms-bridge')],
    ['value' => '179', 'label' => __('Papua New Guinea', 'forms-bridge')],
    ['value' => '180', 'label' => __('Paraguay', 'forms-bridge')],
    ['value' => '181', 'label' => __('Peru', 'forms-bridge')],
    ['value' => '182', 'label' => __('Philippines', 'forms-bridge')],
    ['value' => '183', 'label' => __('Pitcairn Islands', 'forms-bridge')],
    ['value' => '184', 'label' => __('Poland', 'forms-bridge')],
    ['value' => '25', 'label' => __('Portugal', 'forms-bridge')],
    ['value' => '185', 'label' => __('Puerto Rico', 'forms-bridge')],
    ['value' => '186', 'label' => __('Qatar', 'forms-bridge')],
    ['value' => '188', 'label' => __('Romania', 'forms-bridge')],
    ['value' => '19', 'label' => __('Russia', 'forms-bridge')],
    ['value' => '189', 'label' => __('Rwanda', 'forms-bridge')],
    ['value' => '245', 'label' => __('Saint Barthelemy', 'forms-bridge')],
    ['value' => '190', 'label' => __('Saint Helena', 'forms-bridge')],
    ['value' => '191', 'label' => __('Saint Kitts and Nevis', 'forms-bridge')],
    ['value' => '192', 'label' => __('Saint Lucia', 'forms-bridge')],
    ['value' => '246', 'label' => __('Saint Martin', 'forms-bridge')],
    [
        'value' => '193',
        'label' => __('Saint Pierre and Miquelon', 'forms-bridge'),
    ],
    [
        'value' => '194',
        'label' => __('Saint Vincent and Grenadines', 'forms-bridge'),
    ],
    ['value' => '195', 'label' => __('Samoa', 'forms-bridge')],
    ['value' => '196', 'label' => __('San Marino', 'forms-bridge')],
    ['value' => '197', 'label' => __('Sao Tome and Principe', 'forms-bridge')],
    ['value' => '26', 'label' => __('Saudi Arabia', 'forms-bridge')],
    ['value' => '22', 'label' => __('Senegal', 'forms-bridge')],
    ['value' => '198', 'label' => __('Serbia', 'forms-bridge')],
    ['value' => '199', 'label' => __('Seychelles', 'forms-bridge')],
    ['value' => '200', 'label' => __('Sierra Leone', 'forms-bridge')],
    ['value' => '29', 'label' => __('Singapore', 'forms-bridge')],
    ['value' => '301', 'label' => __('Sint Maarten', 'forms-bridge')],
    ['value' => '201', 'label' => __('Slovakia', 'forms-bridge')],
    ['value' => '202', 'label' => __('Slovenia', 'forms-bridge')],
    ['value' => '203', 'label' => __('Solomon Islands', 'forms-bridge')],
    ['value' => '204', 'label' => __('Somalia', 'forms-bridge')],
    ['value' => '205', 'label' => __('South Africa', 'forms-bridge')],
    [
        'value' => '206',
        'label' => __(
            'South Georgia and the South Sandwich Islands',
            'forms-bridge'
        ),
    ],
    ['value' => '129', 'label' => __('South Korea', 'forms-bridge')],
    ['value' => '4', 'label' => __('Spain', 'forms-bridge')],
    ['value' => '207', 'label' => __('Sri Lanka', 'forms-bridge')],
    ['value' => '208', 'label' => __('Sudan', 'forms-bridge')],
    ['value' => '209', 'label' => __('Suriname', 'forms-bridge')],
    ['value' => '210', 'label' => __('Svalbard and Jan Mayen', 'forms-bridge')],
    ['value' => '211', 'label' => __('Swaziland', 'forms-bridge')],
    ['value' => '20', 'label' => __('Sweden', 'forms-bridge')],
    ['value' => '6', 'label' => __('Switzerland', 'forms-bridge')],
    ['value' => '212', 'label' => __('Syrian', 'forms-bridge')],
    ['value' => '213', 'label' => __('Taiwan', 'forms-bridge')],
    ['value' => '214', 'label' => __('Tajikistan', 'forms-bridge')],
    ['value' => '215', 'label' => __('Tanzania', 'forms-bridge')],
    ['value' => '216', 'label' => __('Thailand', 'forms-bridge')],
    ['value' => '217', 'label' => __('Timor-Leste', 'forms-bridge')],
    ['value' => '15', 'label' => __('Togo', 'forms-bridge')],
    ['value' => '218', 'label' => __('Tokelau', 'forms-bridge')],
    ['value' => '219', 'label' => __('Tonga', 'forms-bridge')],
    ['value' => '220', 'label' => __('Trinidad and Tobago', 'forms-bridge')],
    ['value' => '10', 'label' => __('Tunisia', 'forms-bridge')],
    ['value' => '221', 'label' => __('Turkey', 'forms-bridge')],
    ['value' => '222', 'label' => __('Turkmenistan', 'forms-bridge')],
    [
        'value' => '223',
        'label' => __('Turks and Caicos Islands', 'forms-bridge'),
    ],
    ['value' => '224', 'label' => __('Tuvalu', 'forms-bridge')],
    ['value' => '225', 'label' => __('Uganda', 'forms-bridge')],
    ['value' => '226', 'label' => __('Ukraine', 'forms-bridge')],
    ['value' => '227', 'label' => __('United Arab Emirates', 'forms-bridge')],
    ['value' => '7', 'label' => __('United Kingdom', 'forms-bridge')],
    ['value' => '11', 'label' => __('United States', 'forms-bridge')],
    [
        'value' => '228',
        'label' => __('United States Minor Outlying Islands', 'forms-bridge'),
    ],
    ['value' => '229', 'label' => __('Uruguay', 'forms-bridge')],
    ['value' => '230', 'label' => __('Uzbekistan', 'forms-bridge')],
    ['value' => '231', 'label' => __('Vanuatu', 'forms-bridge')],
    ['value' => '232', 'label' => __('Venezuela', 'forms-bridge')],
    ['value' => '233', 'label' => __('Viet Nam', 'forms-bridge')],
    [
        'value' => '234',
        'label' => __('Virgin Islands, British', 'forms-bridge'),
    ],
    ['value' => '235', 'label' => __('Virgin Islands, U.S.', 'forms-bridge')],
    ['value' => '236', 'label' => __('Wallis and Futuna', 'forms-bridge')],
    ['value' => '237', 'label' => __('Western Sahara', 'forms-bridge')],
    ['value' => '238', 'label' => __('Yemen', 'forms-bridge')],
    ['value' => '239', 'label' => __('Zambia', 'forms-bridge')],
    ['value' => '240', 'label' => __('Zimbabwe', 'forms-bridge')],
];
