<?php
/**
 * Class Vtiger_Addon
 *
 * @package formsbridge
 */

namespace FORMS_BRIDGE;

if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

require_once 'class-vtiger-form-bridge.php';
require_once 'hooks.php';

/**
 * Vtiger Addon class.
 *
 * Provides integration with Vtiger CRM Webservice REST API.
 */
class Vtiger_Addon extends Addon {

	/**
	 * Holds the addon's title.
	 *
	 * @var string
	 */
	public const TITLE = 'Vtiger';

	/**
	 * Holds the addon's name.
	 *
	 * @var string
	 */
	public const NAME = 'vtiger';

	/**
	 * Holds the addon's custom bridge class.
	 *
	 * @var string
	 */
	public const BRIDGE = '\FORMS_BRIDGE\Vtiger_Form_Bridge';

	/**
	 * Performs a request against the backend to check the connexion status.
	 *
	 * @param string $backend Target backend name.
	 *
	 * @return boolean
	 */
	public function ping( $backend ) {
		$bridge = new Vtiger_Form_Bridge(
			array(
				'name'     => '__vtiger-' . time(),
				'method'   => 'listtypes',
				'endpoint' => '',
				'backend'  => $backend,
			)
		);

		$response = $bridge->submit();

		if ( is_wp_error( $response ) ) {
			Logger::log( 'Vtiger backend ping error response', Logger::ERROR );
			Logger::log( $response, Logger::ERROR );
			return false;
		}

		return true;
	}

	/**
	 * Performs a query request against the backend module and retrieve the response data.
	 *
	 * @param string $endpoint Target module name.
	 * @param string $backend Target backend name.
	 *
	 * @return array|WP_Error
	 */
	public function fetch( $endpoint, $backend ) {
		$bridge = new Vtiger_Form_Bridge(
			array(
				'name'     => '__vtiger-' . time(),
				'method'   => 'query',
				'endpoint' => $endpoint,
				'backend'  => $backend,
			)
		);

		return $bridge->submit(
			array(
				'query' => "SELECT * FROM {$endpoint};",
			)
		);
	}

	/**
	 * Fetch available modules from the backend.
	 *
	 * @param string      $backend HTTP backend object.
	 * @param string|null $method API method.
	 *
	 * @return array
	 */
	public function get_endpoints( $backend, $method = null ) {
		$bridge = new Vtiger_Form_Bridge(
			array(
				'name'     => '__vtiger-' . time(),
				'method'   => 'listtypes',
				'endpoint' => '',
				'backend'  => $backend,
			)
		);

		$response = $bridge->submit();

		if ( is_wp_error( $response ) ) {
			return array();
		}

		if ( ! isset( $response['data']['result']['types'] ) ) {
			return array();
		}

		return $response['data']['result']['types'];
	}

	/**
	 * Performs an introspection of the backend module and returns API fields
	 * and accepted content type.
	 *
	 * @param string      $module Target module name.
	 * @param string      $backend Target backend name.
	 * @param string|null $method API method.
	 *
	 * @return array List of fields and content type of the module.
	 */
	public function get_endpoint_schema( $module, $backend, $method = null ) {
		if ( 'create' !== $method ) {
			return array();
		}

		$bridge = new Vtiger_Form_Bridge(
			array(
				'name'     => '__vtiger-' . time(),
				'method'   => 'describe',
				'endpoint' => $module,
				'backend'  => $backend,
			)
		);

		$response = $bridge->submit();

		if ( is_wp_error( $response ) ) {
			return array();
		}

		if ( ! isset( $response['data']['result']['fields'] ) ) {
			return array();
		}

		$fields = array();
		foreach ( $response['data']['result']['fields'] as $spec ) {
			if ( ! $spec['editable'] ) {
				continue;
			}

			$type = 'string';

			if ( in_array( $spec['type']['name'], array( 'integer', 'autogenerated' ), true ) ) {
				$type = 'integer';
			} elseif ( in_array( $spec['type']['name'], array( 'double', 'currency' ), true ) ) {
				$type = 'number';
			} elseif ( 'boolean' === $spec['type']['name'] ) {
				$type = 'boolean';
			}

			$schema = array(
				'type'     => $type,
				'required' => $spec['mandatory'],
			);

			$fields[] = array(
				'name'   => $spec['name'],
				'schema' => $schema,
			);
		}

		return $fields;
	}
}

Vtiger_Addon::setup();
